name: Publish Package to NPM

on:
  release:
    types: [created]

permissions:
  contents: read
  checks: write
  pull-requests: write
  issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and test
        uses: ./.github/actions/build-and-test
        with:
          CUCUMBER_PUBLISH_TOKEN: ${{ secrets.CUCUMBER_PUBLISH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: esbuild-deploy-dist
          path: ./packages/esbuild-deploy/dist/

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: esbuild-deploy-dist
          path: ./packages/esbuild-deploy/dist/

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: false
          package_json_file: 'package.json'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish to NPM
        working-directory: ./packages/esbuild-deploy
        run: pnpm publish --report-summary --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Upload publish summary
        uses: actions/upload-artifact@v4
        with:
          name: pnpm-publish-summary.json
          path: ./packages/esbuild-deploy/pnpm-publish-summary.json
